# local.yml

services:
  app:
    build:
      context: .
      dockerfile: ./compose/linkedin/Dockerfile
      args:
        - BUILD_ENV=local
    env_file:
      - .env
    command: /start
    volumes:
      - .:/app
    ports:
      - "5901:5900"
    restart: unless-stopped
